// API

export enum NGXTranslateKeyENUM {
  TODO_TRANSLATION = '**missing translation',

  // NAV
  COMMON_LABEL_ROOT = 'common.label.root',
  COMMON_LABEL_PUBLIC = 'common.label.public',
  COMMON_LABEL_ADMIN = 'common.label.admin',

  // NAV DEMO
  COMMON_LABEL_DEMO = 'common.label.demo',
  COMMON_LABEL_REPOSITORY = 'common.label.repository',
  COMMON_LABEL_UIC = 'common.label.uic',
  COMMON_LABEL_CUSTOM = 'common.label.custom',
  COMMON_LABEL_PRIMENG = 'common.label.primeng',
  COMMON_LABEL_ELASTIC_UI = 'common.label.elasticui',
  COMMON_LABEL_ANGULAR_MATERIAL = 'common.label.angularMaterial',
  COMMON_LABEL_JSON_PLACEHOLDER = 'common.label.jsonPlaceholder',
  COMMON_LABEL_LIBRARY = 'common.label.library',
  COMMON_LABEL_PHOTO = 'common.label.photo',
  COMMON_LABEL_POSTS = 'common.label.posts',
  COMMON_LABEL_AGM_CORE = 'common.label.agmCore',
  COMMON_LABEL_WHATSAPP = 'common.label.whatsapp',
  COMMON_LABEL_GITHUB = 'common.label.github',
  COMMON_LABEL_SUMMARY = 'common.label.summary',
  COMMON_LABEL_IMAGE_MONITORING = 'common.label.imageMonitoring',
  COMMON_LABEL_VQI = 'common.label.vqi',
  COMMON_LABEL_SAKAING = 'common.label.sakaing',
  COMMON_LABEL_AGFA = 'common.label.agfa',
  COMMON_LABEL_FORM = 'common.label.form',
  COMMON_LABEL_WIZARD = 'common.label.wizard',
  COMMON_LABEL_ELEMENTS = 'common.label.elements',
  COMMON_LABEL_COMPONENTS = 'common.label.components',
  COMMON_LABEL_AUTOCOMPLETE = 'common.label.autocomplete',
  COMMON_LABEL_BADGE = 'common.label.badge',
  COMMON_LABEL_BOTTOM_SHEET = 'common.label.bottomSheet',
  COMMON_LABEL_BUTTON = 'common.label.button',
  COMMON_LABEL_BUTTON_TOGGLE = 'common.label.buttonToggle',
  COMMON_LABEL_CARD = 'common.label.card',
  COMMON_LABEL_CHECKBOX = 'common.label.checkbox',
  COMMON_LABEL_CHIPS = 'common.label.chips',
  COMMON_LABEL_CORE = 'common.label.core',
  COMMON_LABEL_DATEPICKER = 'common.label.datepicker',
  COMMON_LABEL_DIALOG = 'common.label.dialog',
  COMMON_LABEL_DIVIDER = 'common.label.divider',
  COMMON_LABEL_EXPANSION_PANEL = 'common.label.expansionPanel',
  COMMON_LABEL_FORM_FIELD = 'common.label.formField',
  COMMON_LABEL_GRID_LIST = 'common.label.gridList',
  COMMON_LABEL_ICON = 'common.label.icon',
  COMMON_LABEL_INPUT = 'common.label.input',
  COMMON_LABEL_LIST = 'common.label.list',
  COMMON_LABEL_MENU = 'common.label.menu',
  COMMON_LABEL_PAGINATOR = 'common.label.paginator',
  COMMON_LABEL_PROGRESS_BAR = 'common.label.progressBar',
  COMMON_LABEL_PROGRESS_SPINNER = 'common.label.progressSpinner',
  COMMON_LABEL_RADIO_BUTTON = 'common.label.radioButton',
  COMMON_LABEL_RIPPLES = 'common.label.ripples',
  COMMON_LABEL_SELECT = 'common.label.select',
  COMMON_LABEL_SIDENAV = 'common.label.sidenav',
  COMMON_LABEL_SLIDE_TOGGLE = 'common.label.slideToggle',
  COMMON_LABEL_SLIDER = 'common.label.slider',
  COMMON_LABEL_SNACKBAR = 'common.label.snackbar',
  COMMON_LABEL_SORT_HEADER = 'common.label.sortHeader',
  COMMON_LABEL_STEPPER = 'common.label.stepper',
  COMMON_LABEL_TABLE = 'common.label.table',
  COMMON_LABEL_TABS = 'common.label.tabs',
  COMMON_LABEL_TOOLBAR = 'common.label.toolbar',
  COMMON_LABEL_TOOLTIP = 'common.label.tooltip',
  COMMON_LABEL_TREE = 'common.label.tree',

  // NAV SHARED
  COMMON_LABEL_REGISTER = 'common.label.register',
  COMMON_LABEL_INBOX = 'common.label.inbox',
  COMMON_LABEL_EDITOR = 'common.label.editor',
  COMMON_LABEL_FORGOT_PASSWORD = 'common.label.forgotpassword',
  COMMON_LABEL_CONTACTS = 'common.label.contacts',
  COMMON_LABEL_CHAT = 'common.label.chat',
  COMMON_LABEL_HOME = 'common.label.home',
  COMMON_LABEL_TODOS = 'common.label.todos',
  COMMON_LABEL_DASHBOARD = 'common.label.dashboard',
  COMMON_LABEL_CRM = 'common.label.crm',
  COMMON_LABEL_DRAG_N_DROP = 'common.label.dragndrop',
  COMMON_LABEL_STATISTICS = 'common.label.statistics',
  COMMON_LABEL_PROFILE = 'common.label.profile',
  COMMON_LABEL_AUTH = 'common.label.auth',
  COMMON_LABEL_DIAGNOSTICS = 'common.label.diagnostics',
  COMMON_LABEL_SETTINGS = 'common.label.settings',

  // COMMON
  COMMON_LABEL_GENERAL = 'common.label.general',
  COMMON_LABEL_TASKBOARD = 'common.label.taskboard',
  COMMON_LABEL_SCHEDULER = 'common.label.scheduler',
  COMMON_LABEL_THEME = 'common.label.theme',
  COMMON_LABEL_LAYOUT = 'common.label.layout',
  COMMON_LABEL_I18N = 'common.label.i18n',
  COMMON_LABEL_DETAILS = 'common.label.details',
  COMMON_LABEL_TITLE = 'common.label.title',
  COMMON_LABEL_ALBUM = 'common.label.album',
  COMMON_LABEL_FILTER = 'common.label.filter',
  COMMON_LABEL_FILTER_PLACEHOLDER = 'common.label.filterPlaceholder',
  COMMON_LABEL_ADDRESS = 'common.label.address',
  COMMON_LABEL_STREET = 'common.label.street',
  COMMON_LABEL_SUITE = 'common.label.suite',
  COMMON_LABEL_ZIPCODE = 'common.label.zipcode',
  COMMON_LABEL_CITY = 'common.label.city',
  COMMON_LABEL_LATITUDE = 'common.label.latitude',
  COMMON_LABEL_LONGITUDE = 'common.label.longitude',
  COMMON_LABEL_WEBSITE = 'common.label.website',
  COMMON_LABEL_USERNAME = 'common.label.username',
  COMMON_LABEL_PASSWORD = 'common.label.password',
  COMMON_LABEL_EMAIL = 'common.label.email',
  COMMON_LABEL_PHONE = 'common.label.phone',
  COMMON_LABEL_BODY = 'common.label.body',
  COMMON_LABEL_COMMENTS = 'common.label.comments',
  COMMON_LABEL_LIKE = 'common.label.like',

  // UI
  COMMON_LABEL_CHARTS = 'common.label.charts',
  COMMON_LABEL_FILE = 'common.label.file',
  COMMON_LABEL_FLOATLABEL = 'common.label.floatlabel',
  COMMON_LABEL_FORMLAYOUT = 'common.label.formlayout',
  COMMON_LABEL_INVALIDSTATE = 'common.label.invalidstate',
  COMMON_LABEL_MEDIA = 'common.label.media',
  COMMON_LABEL_MESSAGE = 'common.label.message',
  COMMON_LABEL_MISC = 'common.label.misc',
  COMMON_LABEL_OVERLAY = 'common.label.overlay',
  COMMON_LABEL_PANEL = 'common.label.panel',
  COMMON_LABEL_ICONS = 'common.label.icons',

  // SHARED
  COMMON_LABEL_CRUD = 'common.label.crud',
  COMMON_LABEL_EMPTY = 'common.label.empty',
  COMMON_LABEL_TIMELINE = 'common.label.timeline',
  COMMON_LABEL_UIKIT = 'common.label.uikit',
  COMMON_LABEL_ERROR = 'common.label.error',
  COMMON_LABEL_ACCESS = 'common.label.access',
  COMMON_LABEL_LOGIN = 'common.label.login',
  COMMON_LABEL_LANDING = 'common.label.landing',
  COMMON_LABEL_NOTFOUND = 'common.label.notfound',
  COMMON_LABEL_BLOCKS = 'common.label.blocks',
  COMMON_LABEL_PAGES = 'common.label.pages',
  COMMON_LABEL_DOCUMENTATION = 'common.label.documentation',

  //GITHUB
  GITHUB_LABEL_CODE = 'github.label.code',
  GITHUB_LABEL_ISSUES = 'github.label.issues',
  GITHUB_LABEL_PULL_REQUESTS = 'github.label.pullRequests',
  GITHUB_LABEL_ACTIONS = 'github.label.actions',
  GITHUB_LABEL_PROJECTS = 'github.label.projects',
  GITHUB_LABEL_SECURITY = 'github.label.security',
  GITHUB_LABEL_INSIGHTS = 'github.label.insights',
  GITHUB_LABEL_WATCH = 'github.label.watch',
  GITHUB_LABEL_FORK = 'github.label.fork',
  GITHUB_LABEL_STAR = 'github.label.star',
  // API
  // MODULES
  FEATURES_LABEL_MODEL = 'features.label.model',
  FEATURE_LABEL_MODEL = 'feature.label.model',
  // USERS
  USERS_LABEL_MODEL = 'users.label.model',
  USERS_LABEL_NAME = 'users.label.name',
  USERS_LABEL_USERS_MANAGEMENT = 'users.label.usersManagement',
  // COMPANY
  COMPANY_LABEL_MODEL = 'company.label.model',
  COMPANY_LABEL_NAME = 'company.label.name',
  COMPANY_LABEL_CATCH_PHRASE = 'company.label.catchPhrase',
  COMPANY_LABEL_BS = 'company.label.bs',
}
