// API

export enum NGXThemeCssENUM {
  // ANGULAR_MATERIAL_DEEPPURPLE_AMBER = 'https://cdn.jsdelivr.net/npm/@angular/material@13.3.0/prebuilt-themes/deeppurple-amber.css',
  // ANGULAR_MATERIAL_INDIGO_PINK = 'https://cdn.jsdelivr.net/npm/@angular/material@13.3.0/prebuilt-themes/indigo-pink.css',
  // ANGULAR_MATERIAL_PINK_BLUEGREY = 'https://cdn.jsdelivr.net/npm/@angular/material@13.3.0/prebuilt-themes/pink-bluegrey.css',
  // ANGULAR_MATERIAL_PURPLE_GREEN = 'https://cdn.jsdelivr.net/npm/@angular/material@13.3.0/prebuilt-themes/purple-green.css',
  PRIME_NG_ARYA_BLUE = './assets/styles/themes/arya-blue/theme.css',
  PRIME_NG_ARYA_GREEN = './assets/styles/themes/arya-green/theme.css',
  PRIME_NG_ARYA_ORANGE = './assets/styles/themes/arya-orange/theme.css',
  PRIME_NG_ARYA_PURPLE = './assets/styles/themes/arya-purple/theme.css',
  PRIME_NG_BOOTSTRAP4_DARK_BLUE = './assets/styles/themes/bootstrap4-dark-blue/theme.css',
  PRIME_NG_BOOTSTRAP4_DARK_PURPLE = './assets/styles/themes/bootstrap4-dark-purple/theme.css',
  PRIME_NG_BOOTSTRAP4_LIGHT_BLUE = './assets/styles/themes/bootstrap4-light-blue/theme.css',
  PRIME_NG_BOOTSTRAP4_LIGHT_PURPLE = './assets/styles/themes/bootstrap4-light-purple/theme.css',
  PRIME_NG_FLUENT_LIGHT = './assets/styles/themes/fluent-light/theme.css',
  PRIME_NG_LARA_DARK_BLUE = './assets/styles/themes/lara-dark-blue/theme.css',
  PRIME_NG_LARA_DARK_INDIGO = './assets/styles/themes/lara-dark-indigo/theme.css',
  PRIME_NG_LARA_DARK_PURPLE = './assets/styles/themes/lara-dark-purple/theme.css',
  PRIME_NG_LARA_DARK_TEAL = './assets/styles/themes/lara-dark-teal/theme.css',
  PRIME_NG_LARA_LIGHT_BLUE = './assets/styles/themes/lara-light-blue/theme.css',
  PRIME_NG_LARA_LIGHT_INDIGO = './assets/styles/themes/lara-light-indigo/theme.css',
  PRIME_NG_LARA_LIGHT_PURPLE = './assets/styles/themes/lara-light-purple/theme.css',
  PRIME_NG_LARA_LIGHT_TEAL = './assets/styles/themes/lara-light-teal/theme.css',
  PRIME_NG_MD_DARK_DEEPPURPLE = './assets/styles/themes/md-dark-deeppurple/theme.css',
  PRIME_NG_MD_DARK_INDIGO = './assets/styles/themes/md-dark-indigo/theme.css',
  PRIME_NG_MD_LIGHT_DEEPPURPLE = './assets/styles/themes/md-light-deeppurple/theme.css',
  PRIME_NG_MD_LIGHT_INDIGO = './assets/styles/themes/md-light-indigo/theme.css',
  PRIME_NG_MDC_DARK_DEEPPURPLE = './assets/styles/themes/mdc-dark-deeppurple/theme.css',
  PRIME_NG_MDC_DARK_INDIGO = './assets/styles/themes/mdc-dark-indigo/theme.css',
  PRIME_NG_MDC_LIGHT_DEEPPURPLE = './assets/styles/themes/mdc-light-deeppurple/theme.css',
  PRIME_NG_MDC_LIGHT_INDIGO = './assets/styles/themes/mdc-light-indigo/theme.css',
  PRIME_NG_SAGA_BLUE = './assets/styles/themes/saga-blue/theme.css',
  PRIME_NG_SAGA_GREEN = './assets/styles/themes/saga-green/theme.css',
  PRIME_NG_SAGA_ORANGE = './assets/styles/themes/saga-orange/theme.css',
  PRIME_NG_SAGA_PURPLE = './assets/styles/themes/saga-purple/theme.css',
  PRIME_NG_TAILWIND_LIGHT = './assets/styles/themes/tailwind-light/theme.css',
  PRIME_NG_VELA_BLUE = './assets/styles/themes/vela-blue/theme.css',
  PRIME_NG_VELA_GREEN = './assets/styles/themes/vela-green/theme.css',
  PRIME_NG_VELA_ORANGE = './assets/styles/themes/vela-orange/theme.css',
  PRIME_NG_VELA_PURPLE = './assets/styles/themes/vela-purple/theme.css',
}
