// API

export enum NGXIconFontFamilyENUM {
  MATERIAL_ICONS = 'material-icons',
  PRIMENG_ICONS = 'pi',
}

export enum NGXAngularMaterialIconCodeENUM {
  LANGUAGE = 'language',
  PREVIEW = 'preview',
  CODE = 'code',
  PALETTE = 'palette',
  LOCAL_LIBRARY = 'local_library',
  PHOTO_LIBRARY = 'photo_library',
  TTY = 'tty',
  MAP = 'map',

  MENU_OPEN = 'menu_open',
  MENU = 'menu',
  APPS = 'apps',
  HELP = 'help',
  NOTIFICATIONS = 'notifications',
  NOTIFICATIONS_ACTIVE = 'notifications_active',

  PUBLIC = 'public',
  CONTACTS = 'contacts',
  CHAT = 'chat',
  FINGERPRINT = 'fingerprint',

  ADMIN_PANEL_SETTINGS = 'admin_panel_settings',
  DASHBOARD = 'dashboard',
  HOME = 'home',
  TASK = 'task',
  PERSON = 'person',
  MANAGE_ACCOUNTS = 'manage_accounts',
  SETTINGS_APPLICATIONS = 'settings_applications',
  DASHBOARD_CUSTOMIZE = 'dashboard_customize',

  CLOSE = 'close',
  SEARCH = 'search',
  TABLE_CHART = 'table_chart',
  NAVIGATE_NEXT = 'navigate_next',
  PHOTO_ALBUM = 'photo_album',
  MEMORY = 'memory',
  MAIL = 'mail',
  PHONE = 'phone',
  LOCATION_CITY = 'location_city',
  THUMB_UP = 'thumb_up',
  COMMENT = 'comment',
  INSIGHTS = 'insights',
  QUERY_STATS = 'query_stats',

  VISIBILITY = 'visibility',
  DEVICE_HUB = 'device_hub',
  STAR_BORDER = 'star_border',
  ADJUST = 'adjust',
  VERTICAL_ALIGN_BOTTOM = 'vertical_align_bottom',
  PLAY_CIRCLE_OUTLINE = 'play_circle_outline',
  SECURITY = 'security',
  INSERT_CHART_OUTLINED = 'insert_chart_outlined',
  LOCK = 'lock',
  LOCK_OPEN = 'lock_open',
  CHECK = 'check',
}

export enum NGXPrimeNGIconCodeENUM {
  PI_AMAZON = 'pi-amazon',
  PI_HOME = 'pi-fw pi-home',
  PI_ID_CARD = 'pi-fw pi-id-card',
  PI_CHECK_SQUARE = 'pi-fw pi-check-square',
  PI_BOOKMARK = 'pi-fw pi-bookmark',
  PI_EXCLAMATION_CIRCLE = 'pi-fw pi-exclamation-circle',
  PI_BOX = 'pi-fw pi-box',
  PI_TABLE = 'pi-fw pi-table',
  PI_CLONE = 'pi-fw pi-clone',
  PI_IMAGE = 'pi-fw pi-image',
  PI_BARS = 'pi-fw pi-bars',
  PI_COMMENT = 'pi-fw pi-comment',
  PI_FILE = 'pi-fw pi-file',
  PI_PIE_CHART = 'pi-fw pi-chart-bar',
  PI_CIRCLE = 'pi-fw pi-circle',
  PI_EYE = 'pi-fw pi-eye',
  PI_GLOBE = 'pi-fw pi-globe',
  PI_PRIME = 'pi-fw pi-prime',
  PI_DESKTOP = 'pi-fw pi-desktop',
  PI_BRIEFCASE = 'pi-fw pi-briefcase',
  PI_USER = 'pi-fw pi-user',
  PI_SIGN_IN = 'pi-fw pi-sign-in',
  PI_TIMES_CIRCLE = 'pi-fw pi-times-circle',
  PI_LOCK = 'pi-fw pi-lock',
  PI_PENCIL = 'pi-fw pi-pencil',
  PI_CALENDAR = 'pi-fw pi-calendar',
  PI_CIRCLE_OFF = 'pi-fw pi-circle-off',
  PI_QUESTION = 'pi-fw pi-question',
  PI_SEARCH = 'pi-fw pi-search',
  PI_TABLET = 'pi-fw pi-tablet',
  PI_LIST = 'pi-fw pi-list',
  PI_SHARE_ALT = 'pi-fw pi-share-alt',
}
